# name: Go

# on:
#   push:
#     branches: [ Main ]
#   pull_request:
#     branches: [ Main ]

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: setup go
#       uses: actions/setup-go@v3
#       with:
#         go-version: 1.18

#     - name: Build binary
#       run: |
#         cd lambda/firehose_and_sqs_controller/data_send_to_firehose_or_sqs/ && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -a -o main main.go && zip main.zip main

#     - name: Test ApiServer Package
#       run: cd lambda/firehose_and_sqs_controller/data_send_to_firehose_or_sqs/ && go test -v

#   build:
#     needs: test
#     runs-on: ubuntu-latest

#     env:
#       function_name: Hello

#     steps:
#     - uses: actions/checkout@v3
#     - name: setup go
#       uses: actions/setup-go@v3
#       with:
#         go-version: 1.18

#     - name: deploy lambda function
#       uses: appleboy/lambda-action@master
#       with:
#         aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws_region: ${{ secrets.AWS_REGION }}
#         function_name: my-function-from-action
#         zip_file: lambda/firehose_and_sqs_controller/data_send_to_firehose_or_sqs/main.zip
#         handler: main
#         runtime: go1.x

